In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [3]:
df = pd.read_excel('/Users/prateek/Desktop/Windows 11 Shared/india-gcc-workforce-analytics/excel/gcc_workforce_analysis.xlsx')

In [4]:
df.head()

,title,jobId,currency,jobUploaded,companyName,tagsAndSkills,experience,salary,location,companyId,ReviewsCount,AggregateRating,jobDescription,minimumSalary,maximumSalary,minimumExperience,maximumExperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,NaN,NaN,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0
2,Opening For Performance Marketing - Chennai,270925007492,INR,6 Days Ago,TVS Credit Services Ltd,"Performance Marketing,User Acquisition,growth ...",12-18 Yrs,Not disclosed,Chennai,1324750,2892.0,4.2,MBA Marketing (preferred Tier II or III B- Sch...,0.0,0.0,12.0,18.0
3,Medical Billing Executive,270925007443,INR,6 Days Ago,GNR Global Services,"Fluent English,Spoken English,Good English Com...",0-3 Yrs,"70,000-2 Lacs PA","Mohali, Chandigarh, Kharar, Zirakpur",123804403,NaN,NaN,Job Title-Medical Billing Executive\nLocation-...,70000.0,200000.0,0.0,3.0
4,Senior Group Product Manager - CNS Therapy,270925007430,INR,6 Days Ago,Cadila Pharmaceuticals,"Product Marketing,CNS,Product Management,Nephr...",5-10 Yrs,8-18 Lacs PA,Ahmedabad,14957,2134.0,3.4,Principal Tasks & Responsibilities : (Please w...,800000.0,1800000.0,5.0,10.0

In [6]:
df.shape

(97929, 17)

In [7]:
df.columns

Index(['title', 'jobId', 'currency', 'jobUploaded', 'companyName',
       'tagsAndSkills', 'experience', 'salary', 'location', 'companyId',
       'ReviewsCount', 'AggregateRating', 'jobDescription', 'minimumSalary',
       'maximumSalary', 'minimumExperience', 'maximumExperience'],
      dtype='str')

In [8]:
df.columns.tolist()

['title',
 'jobId',
 'currency',
 'jobUploaded',
 'companyName',
 'tagsAndSkills',
 'experience',
 'salary',
 'location',
 'companyId',
 'ReviewsCount',
 'AggregateRating',
 'jobDescription',
 'minimumSalary',
 'maximumSalary',
 'minimumExperience',
 'maximumExperience']

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97929 entries, 0 to 97928
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              97929 non-null  str
 1   jobId              97929 non-null  int64
 2   currency           97929 non-null  str
 3   jobUploaded        97929 non-null  str
 4   companyName        97925 non-null  str
 5   tagsAndSkills      97358 non-null  str
 6   experience         95824 non-null  str
 7   salary             97929 non-null  str
 8   location           97929 non-null  str
 9   companyId          97929 non-null  int64
 10  ReviewsCount       62677 non-null  float64
 11  AggregateRating    62677 non-null  float64
 12  jobDescription     97929 non-null  str
 13  minimumSalary      97358 non-null  float64
 14  maximumSalary      97358 non-null  float64
 15  minimumExperience  97358 non-null  float64
 16  maximumExperience  97358 non-null  float64
dtypes: float64(6), int64(2), str(9)
memory usage: 12.7 MB

In [12]:
## Missing-value analysis

In [13]:
df.isnull().sum()

title                    0
jobId                    0
currency                 0
jobUploaded              0
companyName              4
tagsAndSkills          571
experience            2105
salary                   0
location                 0
companyId                0
ReviewsCount         35252
AggregateRating      35252
jobDescription           0
minimumSalary          571
maximumSalary          571
minimumExperience      571
maximumExperience      571
dtype: int64

In [14]:
missing_values = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percentage": df.isnull().mean() * 100
})

missing_values.sort_values(
    by="missing_percentage",
    ascending=False
)

                   missing_count  missing_percentage
ReviewsCount               35252           35.997508
AggregateRating            35252           35.997508
experience                  2105            2.149516
maximumExperience            571            0.583075
minimumExperience            571            0.583075
maximumSalary                571            0.583075
tagsAndSkills                571            0.583075
minimumSalary                571            0.583075
companyName                    4            0.004085
jobDescription                 0            0.000000
title                          0            0.000000
companyId                      0            0.000000
jobId                          0            0.000000
salary                         0            0.000000
jobUploaded                    0            0.000000
currency                       0            0.000000
location                       0            0.000000

In [15]:
## Checking Duplicate Rows

In [16]:
df.duplicated().sum()

np.int64(247)

In [17]:
df["jobId"].duplicated().sum()

np.int64(250)

In [18]:
df.describe()

,jobId,companyId,ReviewsCount,AggregateRating,minimumSalary,maximumSalary,minimumExperience,maximumExperience
count,9.792900e+04,9.792900e+04,62677.000000,62677.000000,9.735800e+04,9.735800e+04,97358.000000,97358.000000
mean,2.069854e+11,2.784642e+07,14662.590264,3.679048,1.983092e+05,3.186096e+05,3.957744,7.732647
std,9.987860e+10,4.979184e+07,24744.514682,0.484096,5.640765e+05,8.417336e+05,3.581196,4.500161
min,1.012500e+10,3.000000e+00,2.000000,1.000000,0.000000e+00,0.000000e+00,0.000000,0.000000
25%,1.808250e+11,2.339390e+05,65.000000,3.500000,0.000000e+00,0.000000e+00,1.000000,5.000000
50%,2.508250e+11,2.892790e+06,962.000000,3.700000,0.000000e+00,0.000000e+00,3.000000,7.000000
75%,2.808250e+11,6.398332e+06,12826.000000,3.900000,2.000000e+05,3.750000e+05,5.000000,10.000000
max,3.112240e+11,1.251422e+08,104449.000000,5.000000,7.000000e+07,9.500000e+07,30.000000,35.000000

In [19]:
df.describe(include="object")

/var/folders/r_/dkxgv72x363bpkl_6vsh9s800000gn/T/ipykernel_13270/702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,title,currency,jobUploaded,companyName,tagsAndSkills,experience,salary,location,jobDescription
count,97929,97929,97929,97925,97358,95824,97929,97929,97929
unique,55104,2,30,18668,84307,287,1339,10066,80679
top,Application Developer,INR,4 Days Ago,Accenture,"Retail,Lead generation,Forex,Investment produc...",5-10 Yrs,Not disclosed,Bengaluru,Disclaimer: This job description has been sour...
freq,2039,97800,13973,8204,116,6448,64076,16823,382

In [20]:
df["location"].nunique()

10066

In [22]:
df["location"].value_counts().head(20)

location
Bengaluru                        16823
Hyderabad                         7669
Pune                              6112
Chennai                           4431
Gurugram                          4233
Mumbai                            4157
Noida                             2695
Remote                            1961
Ahmedabad                         1726
Navi Mumbai                       1453
Kolkata                           1049
Hyderabad, Chennai, Bengaluru     1037
Hybrid - Bengaluru                 946
Jaipur                             821
Coimbatore                         618
Hybrid - Hyderabad                 576
Kochi                              528
Vadodara                           528
Hybrid - Pune                      480
Thane                              410
Name: count, dtype: int64